version: "3.8"

networks:
  skynet:

volumes:
  influxdb_data:
  grafana_data:

services:
  influxdb:
    image: influxdb
    container_name: influxdb
    networks:
      - skynet
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: 637Ue57CJ!CL
      DOCKER_INFLUXDB_INIT_ORG: temp-monitor-org
      DOCKER_INFLUXDB_INIT_BUCKET: temp-monitor-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: WkoTClqWxUZ_zCoUn3RZsMNVehVG8MeYFy_R9yaBUEbwmxgAxvJVdIkMdHJhVmXqoJ6jJxWAJXoA3sPWgMPxKQ==

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - skynet
    links:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=m327Di#*5*sb

  monitor:
    image: monitor
    container_name: monitor
    build: .
    restart: on-failure
    networks:
      - skynet
    links:
      - influxdb
    depends_on:
      - grafana
      - influxdb
    environment:
      INFLUXDB_TOKEN: WkoTClqWxUZ_zCoUn3RZsMNVehVG8MeYFy_R9yaBUEbwmxgAxvJVdIkMdHJhVmXqoJ6jJxWAJXoA3sPWgMPxKQ==
      INFLUXDB_BUCKET: temp-monitor-bucket
      INFLUXDB_ORG: temp-monitor-org